apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-cleanup
  namespace: {{ include "osm.namespace" . }}
  annotations:
    helm.sh/hook: post-delete
  labels:
    {{- include "osm.labels" . | nindent 4 }}
spec:
  serviceAccountName: {{ .Release.Name }}-cleanup
  restartPolicy: OnFailure
  containers:
  - name: garbage-collector
    image: bitnami/kubectl
    imagePullPolicy: IfNotPresent
    command:
            - sh
            - -c
            - >
             kubectl delete --ignore-not-found meshconfig -n '{{ include "osm.namespace" . }}' osm-mesh-config;
             kubectl delete crd meshconfigs.config.openservicemesh.io --ignore-not-found;